version: '3.7'
volumes:
  dynamodb:
    driver: local
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    volumes:
      - ./data:/home/dynamodblocal/data
    ports:
      - "8888:8000"
    command:
      -jar DynamoDBLocal.jar -sharedDb -dbPath ./data -optimizeDbBeforeStartup
